### ISSUE TITLE
Incompatibility with Serde 1.0.0

### ISSUE THREAD

**Issue by manonthemat** [livioribeiro/rusted-cypher#15]
After updating to the recently released 1.0.0 version of `serde`, `serde_json`, and `serde_derive`, I'm getting errors of this kind:

```
`the trait `rusted_cypher::<unnamed>::Serialize` is not implemented for `{struct name here}``
```

**Comment by livioribeiro** [comment]
I published a version that is compatible with serde 1.0.

Could you test it and tell if that worked for you?

**Comment by manonthemat** [comment]
Thank you for publishing rusted_cypher 1.1.0.

Now I'm getting this error message: ``` the trait `serde::ser::Serialize` is not implemented for `Media` ```

Media is a simple struct for which I use `#[derive(Serialize)]`:
```rust
#[derive(Debug, Serialize, Deserialize)]                                                                                               
struct Media {                                                                                                                         
    id: String,                                                                                                                        
    rating: u16,                                                                                                                       
    release_date: i32,                                                                                                                 
    year: i16,                                                                                                                         
} 
```

**Comment by livioribeiro** [comment]
I did a quick test and everything went OK.

You could try running

    cargo clean
    cargo update

and see if it helps.

I will need more information to find out what the problem is, but I think it is not related to rusted_cypher.

And thanks for reporting this issue.

**Comment by manonthemat** [comment]
I do believe that this isn't an issue caused by rusted_cypher any longer. I'm using [Rocket](https://github.com/SergioBenitez/Rocket) for my project and noticed, that even the most recent version of the rocket_contrib crate (0.2.6 at this time) installs older versions of serde and serde_json. I assume this is where this new error originates from.

Thank you for the quick fix!
