### ISSUE TITLE
r2d2 support

### ISSUE THREAD

**Issue by flosse** [livioribeiro/rusted-cypher#2]
I started with a first snippet to use your library with r2d2: https://github.com/flosse/r2d2-cypher.
Do you have an idea how I can check if the connection of the `GraphClient` is still alive? Is there a cypher query that always works with minimal payload?

**Comment by livioribeiro** [comment]
I just tested `RETURN 1` on neo4j web interface and it worked. I don't know if there is a better way but this will probably do the job.

**Comment by flosse** [comment]
It seems to work :) Tank you!
