### ISSUE TITLE
rustc_serialize support

### ISSUE THREAD

**Issue by flosse** [livioribeiro/rusted-cypher#5]
At the moment the library forces the user to use `serde` to deserialize the data. That implies a project which depends on `rusted-cyper` can't compile with the stable compiler unless it implements the trait for each struct or use the "syntex hack".
Could we provide a function like

```rust
pub fn get_rustc<T: rustc_serialize::Decodable>(&self, column: &str) -> Result<T, GraphError>
```

at least as long as rust doesn't accept compiler plugins within stable releases?

**Comment by flosse** [comment]
never mind ;-)

**Comment by livioribeiro** [comment]
I started with `rustc-serialize` but then switched to `serde` in order to support sending multiple statements, since each statement can have diferente return types I had no option but to deserialize the result of each statement into a `rustc_serialize::json::Json`, but `rustc-serialize` don't support that. However, `serde` supports deserializing to `serde_json::value::Value`.

If there is a way to achieve this using `rustc-serialize`, I would switch from `serde` until it can build on stable.

**Comment by flosse** [comment]
> However, serde supports deserializing to serde_json::value::Value

yes, actually that's one of the workaround I tried:

```rust
let x_value = &row.get::<Value>("x").unwrap();
let x_json_string = serde_json::to_string(&x_value).unwrap();
let x = json::decode::<Foo>(&x_json_string).unwrap();
```
But as long as only a few entities are used, a manual implementation can do the job: 

```rust
impl Deserialize for Foo {
  fn deserialize<D>(deserializer: &mut D) -> Result<Foo, D::Error> where D: Deserializer {
    deserializer.visit(FooVisitor)
  }
}

struct FooVisitor;

impl Visitor for FooVisitor {
    type Value = Foo;

    fn visit_string<E>(&mut self, value: String) -> Result<Foo, E>
        where E: Error,
    {
        json::decode::<Foo>(&value).map_err(|err| Error::syntax(&*err.to_string()))
    }
}
```

Do you have any other solutions in mind?

**Comment by livioribeiro** [comment]
I'm sorry, I can't think of any other solution right now.

I could try to support `rustc-serialize` without multiple statements though a feature gate, like this:

```toml
[dependencies]
rusted_cypher = { version =  "*", features = ["rustc-serialize"] }
```

What do you think?

**Comment by flosse** [comment]
Great idea! That would be very comfortable to use :)

**Comment by livioribeiro** [comment]
Support for `rustc-serialize` is working on branch `feature/rustc-serialize`. It accepts structs implementing `rustc-serialize` traits on both `Statement` and `Row`.

It's a working in progress but I think it should work.

I'm reopening this issue since it is an useful feature.

**Comment by flosse** [comment]
> Support for `rustc-serialize` is working on branch `feature/rustc-serialize`.

This is super awesome!

> It's a working in progress

so what i missing?

**Comment by livioribeiro** [comment]
Nothing is missing, I hope, I just need to review the code, fix a bug and figure out how to write documentation for this feature.

**Comment by livioribeiro** [comment]
Despite being functional and passing the tests, the code to became ugly and harder to maintain, so I created [another project](https://github.com/livioribeiro/rusted-cypher-lite) that works with `rustc-serialize`.

The api is a little bit different and not so elegant.

I would be grateful if you could try it out and tell if that works for you.

**Comment by flosse** [comment]
> [...], so I created another project that works with rustc-serialize.

are you sure you want to maintain a separate fork?

I'm using 8354034f127e12f8c33318ec226ed8dbe247ca85 and it seems to work :) So what are the downsides of it?
Here is a new related question: https://www.reddit.com/r/rust/comments/3v2k37/can_a_library_support_both_rustcserialize_and/
Maybe there will be some interesting answers.

> I would be grateful if you could try it out and tell if that works for you.

Of course I'll test it but unfortunately at the earliest next week :-\

**Comment by livioribeiro** [comment]
The only downside is that it might harm performance a little bit (didn't check it).
However, since you're using Rust and usually the network is the bottleneck, it may not be a problem.

**Comment by flosse** [comment]
> The only downside is that it might harm performance a little bit (didn't check it).
However, since you're using Rust and usually the network is the bottleneck, it may not be a problem.

I totally agree. Moreover at the moment I'm using `nickel` that is based on `hyper` which doesn't support non-blocking I/O yet, so I there there a several bottlenecks ;-)

And I'd rather use a stable but not so fast application that a blazing fast server that is blazing fast down and is hard to maintain ;-)

**Comment by flosse** [comment]
And here is an other thread concerning this topic:
https://www.reddit.com/r/rust/comments/3we7fr/how_do_you_deal_with_upstream_crates_introducing/

**Comment by livioribeiro** [comment]
I'm really glad to hear that this is working for :-)

I believe the performance penalty for using `rustc-serialize` feature should be minimal since it only affects adding parameters to statements and retrieving values from results, but again, I didn't check that.

This is the best solution I could find without rewriting the crate.

Anyway, the changes are published!

**Comment by flosse** [comment]
> Anyway, the changes are published!

awesome! Thanks a lot!
