### ISSUE TITLE
working with NULL

### ISSUE THREAD

**Issue by flosse** [livioribeiro/rusted-cypher#7]
Cypher does not allow to use `null` as parameter type. Unfortunately a serialized struct with a `Option<T>` field contains `null` values.
So e.g. this would fail:
```rust
struct Foo {
  id:  Option<u32>,
  name: String
}
```
```rust
let x = Foo{id: None, name: "foo".to_string()};
graph.cypher()
  .exec(cypher_stmt!("CREATE (e:Entry {entry}) RETURN e.id" {
  "entry" => &x }))
```
Do you have a recommendation for handling such a case?

**Comment by livioribeiro** [comment]
It seems that the query is causing neo4j to throw an exception.

Logging shows that the query sent is:

```json
{
    "statements": [
        {
            "statement": "CREATE (n:Entry {entry}) return n.id",
            "parameters": {
                "entry": {
                    "id": null,
                    "name": "foo"
                }
            }
        }
    ]
}
```
This may be a problem with neo4j itself, I'll try to find out something about this and maybe file an issue on neo4j repo.

Thanks.

**Comment by flosse** [comment]
> This may be a problem with neo4j itself

actually it's a feature ;-) So neo4j won't change the behavior! So the current solution is to either check it in the cypher statement or to resolve the `Option` value manually by using `my_val.unwrap_or("".to_string())`
I think `rusted_cypher` can't help there, so I'll close this issue.

**Comment by livioribeiro** [comment]
I was about to answer about that :smile:

**Comment by flosse** [comment]
BTW: If you're using the `SET` statement you don't have this problem :)

**Comment by livioribeiro** [comment]
I hope they fix that feature :)
